management:
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
  server:
    port: 8088
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired

missyou:
  security:
    jwt-key: 888888888
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host:
    pay-callback-path: /v1/payment/wx/notify
